### ISSUE TITLE
PIP Install injective-py breaks (error output below)

### ISSUE THREAD

**Issue by chagelstein** [InjectiveLabs/iAgent#10]
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      WARNING: Use build.verbose instead of cmake.verbose for scikit-build-core >= 0.10
      *** scikit-build-core 0.10.7 using CMake 3.31.2 (wheel)
      *** Configuring CMake...
      loading initial cache file C:\Users\iAGENT-Novice\AppData\Local\Temp\tmp622nq_i7\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\iAGENT-Novice\AI_Projects\iAgent\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\iAGENT-Novice\AI_Projects\iAgent\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\iAGENT-Novice\AI_Projects\iAgent\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\iAGENT-Novice\AppData\Local\Temp\pip-build-env-xg6ajnga\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\iAGENT-Novice\AppData\Local\Temp\pip-build-env-xg6ajnga\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 147, in build
          build_hook.initialize(version, build_data)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\iAGENT-Novice\AppData\Local\Temp\pip-build-env-xg6ajnga\overlay\Lib\site-packages\scikit_build_core\hatch\plugin.py", line 124, in initialize
          self._initialize(build_data=build_data)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\iAGENT-Novice\AppData\Local\Temp\pip-build-env-xg6ajnga\overlay\Lib\site-packages\scikit_build_core\hatch\plugin.py", line 226, in _initialize
          builder.configure(
          ~~~~~~~~~~~~~~~~~^
              defines=defines,
              ^^^^^^^^^^^^^^^^
          ...<2 lines>...
              version=Version(self.build_config.builder.metadata.version),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\iAGENT-Novice\AppData\Local\Temp\pip-build-env-xg6ajnga\overlay\Lib\site-packages\scikit_build_core\builder\builder.py", line 255, in configure
          self.config.configure(
          ~~~~~~~~~~~~~~~~~~~~~^
              defines=cmake_defines,
              ^^^^^^^^^^^^^^^^^^^^^^
              cmake_args=[*self.get_cmake_args(), *configure_args],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\iAGENT-Novice\AppData\Local\Temp\pip-build-env-xg6ajnga\overlay\Lib\site-packages\scikit_build_core\cmake.py", line 242, in configure
          raise FailedLiveProcessError(msg) from None
      scikit_build_core.errors.FailedLiveProcessError: CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by chagelstein** [comment]
Need to install Visual Studio Build Tools 2022 17.12.3 > Workloads > Desktop development with C++
Need to install Visual Studio Build Tools 2022 17.12.3 > Workloads > Windows applications development build tools
Need to install Visual Studio Build Tools 2022 17.12.3 > Workloads > Visual Studio extension development

**Comment by chagelstein** [comment]
Need to do additional work to have the resolve the error
