### ISSUE TITLE
Unable to locate package python3-grpc

### ISSUE THREAD

**Issue by chagelstein** [InjectiveLabs/iAgent#9]
Traceback (most recent call last):
  File "/mnt/c/iAgent/agent_server.py", line 7, in <module>
    from injective_functions.factory import InjectiveClientFactory
  File "/mnt/c/iAgent/injective_functions/factory.py", line 2, in <module>
    from injective_functions.utils.initializers import ChainInteractor
  File "/mnt/c/iAgent/injective_functions/utils/initializers.py", line 1, in <module>
    from grpc import RpcError
ModuleNotFoundError: No module named 'grpc'
atomics@Sophie:/mnt/c/iAgent$ sudo apt install python3-grpc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**E: Unable to locate package python3-grpc**
atomics@Sophie:/mnt/c/iAgent$

**Comment by chagelstein** [comment]
module is incorrectly named.
